/* Copyright 2020 ZSA Technology Labs, Inc <@zsa>
 * Copyright 2020 Jack Humbert <jack.humb@gmail.com>
 * Copyright 2020 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */



#include QMK_KEYBOARD_H
#include "version.h"

enum layers {
    BASE,  // base/QWERTY layer
    SYMB,  // symbols
    NUMBER,  // numbers and emojis
    MOUSE,  // mouse and RGB controls
};

#define BAS_LYR TO(BASE)
#define SYM_LYR TG(SYMB)
#define NUM_LYR TG(NUMBER)
#define MSE_LYR TG(MOUSE)

#define X_____X KC_TRNS
#define ___X___ KC_NO

/* ALT === OPT */
#define L_PANE LCMD(LOPT(KC_LEFT))
#define R_PANE LCMD(LOPT(KC_RIGHT))
#define OPT_L LOPT(KC_LEFT)
#define OPT_R LOPT(KC_RIGHT)
#define CMD_L LCMD(KC_LEFT)
#define CMD_R LCMD(KC_RIGHT)

#define SW_INPT LCTL(KC_SPACE)
#define CMD_TILD LCMD(KC_TILD)

// Home Row Mod-Taps
#define HOME_A LCTL_T(KC_A)
#define HOME_S LOPT_T(KC_S)
#define HOME_D LCMD_T(KC_D)
#define HOME_K LCMD_T(KC_K)
#define HOME_L ROPT_T(KC_L)
#define HOME_SCLN RCTL_T(KC_SCLN)

// Home Row Layer Taps
#define HOME_F LT(SYMB, KC_F)
#define HOME_J LT(SYMB, KC_J)
#define HOME_G LT(NUMBER, KC_G)
#define HOME_H LT(NUMBER, KC_H)

// Lower Home Row Layer Taps
#define HOME_V LT(MOUSE, KC_V)
#define HOME_M LT(MOUSE, KC_M)

// Thumb Mod-Taps
#define THUM_BSPC LSFT_T(KC_BSPC)
#define THUM_SPC  RSFT_T(KC_SPC)
#define THUM_TAB HYPR_T(KC_TAB)
#define THUM_ENT MEH_T(KC_ENT)

enum custom_keycodes {
  PLACEHOLDER = SAFE_RANGE, // can always be here
  VRSN,
  LED_BLU, // HSV_172_255_255
  LED_GRN, // HSV_86_255_128
  LED_RED, // HSV_0_255_255
  LED_ORNG, // HSV_27_255_255
  LED_PUPL,
  L_ERB,
  R_ERB,
  // Emojis
  CLAP,
  COFFEE,
  L_ARROW,
  D_ARROW,
  R_ARROW,
  U_ARROW,
  LAUGH,
  MINUS_ONE,
  NEUTRAL,
  PLUS_ONE,
  SAD,
  SINGLE_ARROW,
  SMILE,
  TROLL,
  WINK,
  // MS Teams Emojis
  TM_100,
  TM_BOW,
  TM_CAKE,
  TM_CLAP,
  TM_CMARK,
  TM_COFE,
  TM_CSFG, // crossed fingers
  TM_EXPH, // exploding head
  TM_EYES,
  TM_HEART,
  TM_OKAY,
  TM_PALM, // face palm
  TM_PRAY,
  TM_P_ONE, // +1
  TM_SMILE,
  TM_SURP, // surprised
  TM_TADA,
  TM_TEA,
  TM_THINK,
  TM_WAVE,
};

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /*                                                                                     generated by [keymapviz] */
    // Base QWERTY Layer
    [BASE] = LAYOUT(
            KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,   ___X___,       ___X___, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,     KC_MINS,
            KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,   NUM_LYR,       MSE_LYR, KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,     KC_BSLS,
            KC_ESC,  HOME_A,  HOME_S,  HOME_D,  HOME_F,  HOME_G, SYM_LYR,       SYM_LYR, HOME_H,  HOME_J,  HOME_K,  HOME_L,  HOME_SCLN, KC_QUOT,
            ___X___, KC_Z,    KC_X,    KC_C,    HOME_V,  KC_B,                           KC_N,    HOME_M,  KC_COMM, KC_DOT,  KC_SLSH,  KC_RSFT,
            _______, _______, _______, _______, _______,         ___X___,       _______,          _______, _______, _______, _______,  _______,
                                            THUM_BSPC, THUM_TAB, CW_TOGG,       _______, THUM_ENT, THUM_SPC
            ),

    /*                                                                                     generated by [keymapviz] */
    // Symbol/Fn Layer
    [SYMB] = LAYOUT(
            VRSN,    KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   ___X___,       ___X___, KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,
            _______, KC_BSLS, KC_AT,   KC_PLUS, KC_MINS, KC_PERC, _______,       _______, KC_LBRC, KC_LPRN, KC_LCBR, L_ERB,   ___X___, KC_F12,
            _______, KC_CIRC, KC_DLR,  KC_ASTR, KC_EQL,  KC_HASH, _______,       _______, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, KC_GRV,  CMD_TILD,
            _______, _______, KC_AMPR, KC_EXLM, KC_UNDS, KC_PIPE,                         KC_RBRC, KC_RPRN, KC_RCBR, R_ERB,   KC_TILD, _______,
            ___X___, ___X___, ___X___, ___X___, ___X___,          _______,       _______,          ___X___, ___X___, ___X___, ___X___, ___X___,
                                                  CMD_L,  CMD_R,  _______,       _______,  CMD_L,  CMD_R
            ),

    /*                                                                                     generated by [keymapviz] */
    // Number/Emoji Layer
    [NUMBER] = LAYOUT(
          _______, _______, _______,  _______, _______,  _______, ___X___,       ___X___, _______, _______, _______, _______, _______, _______,
          _______, TM_HEART,TM_TADA,  TM_PALM, TM_EXPH,  TM_SURP, _______,       _______, TM_CLAP, KC_P7,   KC_P8,   KC_P9,   TM_COFE, _______,
          _______, TM_EYES, TM_CMARK, TM_100,  TM_PRAY,  TM_BOW,  _______,       _______, TM_WAVE, KC_P4,   KC_P5,   KC_P6,   TM_SMILE,TM_P_ONE,
          _______, _______, TM_CAKE,  TM_OKAY, TM_THINK, TM_CSFG,                         KC_P0,   KC_P1,   KC_P2,   KC_P3,   TM_TEA,  _______,
          ___X___, ___X___, ___X___,  ___X___, ___X___,           _______,       _______,          ___X___, ___X___, ___X___, ___X___, ___X___,
                                                   OPT_L,  OPT_R, _______,       _______,  OPT_L,  OPT_R
          ),

    /*                                                                                     generated by [keymapviz] */
    // Mouse/RGB control Layer
    [MOUSE] = LAYOUT(
          // Left Hand
          AU_TOGG, ___X___, ___X___, ___X___, ___X___,  ___X___, _______,        _______, _______, _______, _______, _______, _______, QK_BOOT,
          _______, RGB_SAI, RGB_SAD, RGB_MOD, RGB_RMOD, RGB_M_P, _______,        _______, _______, _______, _______, _______, _______, _______,
          _______, RGB_VAI, RGB_VAD, LED_RED, LED_GRN,  RGB_TOG, _______,        _______, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, _______, _______,
          _______, RGB_HUI, RGB_HUD, LED_BLU, LED_ORNG, LED_PUPL,                         _______, KC_BTN1, KC_BTN2, _______, _______, _______,
          ___X___, ___X___, ___X___, ___X___, ___X___,           _______,        _______,          _______, _______, _______, _______, _______,
                                                 L_PANE, R_PANE, _______,        _______, L_PANE,  R_PANE
          )
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        switch (keycode) {
            // dynamically generate these.
            case VRSN:
                SEND_STRING (QMK_KEYBOARD "/" QMK_KEYMAP " @ " QMK_VERSION);
                return false;
            case LED_BLU:
                rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
                rgb_matrix_sethsv_noeeprom(HSV_BLUE);
                return false;

            case LED_GRN:
                rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
                rgb_matrix_sethsv_noeeprom(HSV_GREEN);
                return false;

            case LED_RED:
                rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
                rgb_matrix_sethsv_noeeprom(HSV_RED);
                return false;

            case LED_ORNG:
                rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
                rgb_matrix_sethsv_noeeprom(HSV_ORANGE);
                return false;

            case LED_PUPL:
                rgb_matrix_mode_noeeprom(1);
                rgb_matrix_sethsv_noeeprom(HSV_PURPLE);
                return false;

            case L_ERB:
                SEND_STRING("<%=");
                return false;

            case R_ERB:
                SEND_STRING("%>");
                return false;

            case CLAP:
                SEND_STRING(":clap:");
                return false;

            case COFFEE:
                SEND_STRING(":coffee:");
                return false;

            case D_ARROW:
                SEND_STRING(":arrow_down:");
                return false;

            case LAUGH:
                SEND_STRING(":joy:");
                return false;

            case L_ARROW:
                SEND_STRING(":arrow_left:");
                return false;

            case MINUS_ONE:
                SEND_STRING(":-1:");
                return false;

            case NEUTRAL:
                SEND_STRING(":neutral:");
                return false;

            case PLUS_ONE:
                SEND_STRING(":+1:");
                return false;

            case R_ARROW:
                SEND_STRING(":arrow_right:");
                return false;

            case SAD:
                SEND_STRING(":disappointed:");
                return false;

            case SMILE:
                SEND_STRING(":smile:");
                return false;

            case TROLL:
                SEND_STRING(":trollface:");
                return false;

            case U_ARROW:
                SEND_STRING(":arrow_up:");
                return false;

            case WINK:
                SEND_STRING(":wink:");
                return false;

                // MS Teams Emojis
            case TM_100:
                SEND_STRING("(hundredpoints)");
                return false;

            case TM_BOW:
                SEND_STRING("(manbowing)");
                return false;

            case TM_CAKE:
                SEND_STRING("(cake)");
                return false;

            case TM_CLAP:
                SEND_STRING("(clap)");
                return false;

            case TM_CMARK:
                SEND_STRING("(checkmarkbutton)");
                return false;

            case TM_COFE:
                SEND_STRING("(coffee)");
                return false;

            case TM_CSFG:
                SEND_STRING("(crossedfingers)");
                return false;

            case TM_EXPH:
                SEND_STRING("(explodinghead)");
                return false;

            case TM_EYES:
                SEND_STRING("(eyes)");
                return false;

            case TM_HEART:
                SEND_STRING("(heart)");
                return false;

            case TM_PALM:
                SEND_STRING("(facepalm)");
                return false;

            case TM_OKAY:
                SEND_STRING("(ok)");
                return false;

            case TM_PRAY:
                SEND_STRING("(pray)");
                return false;

            case TM_P_ONE:
                SEND_STRING("(y)");
                return false;

            case TM_SMILE:
                SEND_STRING(":)");
                return false;

            case TM_SURP:
                SEND_STRING(":O");
                return false;

            case TM_TADA:
                SEND_STRING("(partypopper)");
                return false;

            case TM_TEA:
                SEND_STRING("(chai)");
                return false;

            case TM_THINK:
                SEND_STRING("(thinkingface)");
                return false;

            case TM_WAVE:
                SEND_STRING("(wavinghand)");
                return false;
        }
    }

    return true;
};
